var allStates = [
{mapID: "HI", nameID: "HI"},
{mapID: "AK", nameID: "AK"},
{mapID: "FL", nameID: "FL"},
{mapID: "MI-", nameID: "MI"},
{mapID: "SP-", nameID: "SP"},
{mapID: "ME", nameID: "ME"},
{mapID: "NY", nameID: "NY"},
{mapID: "PA", nameID: "PA"},
{mapID: "VA", nameID: "VA"},
{mapID: "WV", nameID: "WV"},
{mapID: "OH", nameID: "OH"},
{mapID: "IN", nameID: "IN"},
{mapID: "IL", nameID: "IL"},
{mapID: "WI", nameID: "WI"},
{mapID: "NC", nameID: "NC"},
{mapID: "TN", nameID: "TN"},
{mapID: "AR", nameID: "AR"},
{mapID: "MO", nameID: "MO"},
{mapID: "GA", nameID: "GA"},
{mapID: "SC", nameID: "SC"},
{mapID: "KY", nameID: "KY"},
{mapID: "AL", nameID: "AL"},
{mapID: "LA", nameID: "LA"},
{mapID: "MS", nameID: "MS"},
{mapID: "IA", nameID: "IA"},
{mapID: "MN", nameID: "MN"},
{mapID: "OK", nameID: "OK"},
{mapID: "TX", nameID: "TX"},
{mapID: "NM", nameID: "NM"},
{mapID: "KS", nameID: "KS"},
{mapID: "NE", nameID: "NE"},
{mapID: "SD", nameID: "SD"},
{mapID: "ND", nameID: "ND"},
{mapID: "WY", nameID: "WY"},
{mapID: "MT", nameID: "MT"},
{mapID: "CO", nameID: "CO"},
{mapID: "ID", nameID: "ID"},
{mapID: "UT", nameID: "UT"},
{mapID: "AZ", nameID: "AZ"},
{mapID: "NV", nameID: "NV"},
{mapID: "OR", nameID: "OR"},
{mapID: "WA", nameID: "WA"},
{mapID: "CA", nameID: "CA"},
{mapID: "NH", nameID: "NH"},
{mapID: "VT", nameID: "VT"},
{mapID: "RI", nameID: "RI"},
{mapID: "CT", nameID: "CT"},
{mapID: "NJ", nameID: "NJ"},
{mapID: "DE", nameID: "DE"},
{mapID: "MD", nameID: "MD"},
{mapID: "DC", nameID: "DC"},
{mapID: "MA", nameID: "MA"}
];



var stateNames = [
{name: "Alabama", id: "AL"},
{name: "Alaska", id: "AK"},
{name: "Arizona", id: "AZ"},
{name: "Arkansas", id: "AR"},
{name: "California", id: "CA"},
{name: "Colorado", id: "CO"},
{name: "Connecticut", id: "CT"},
{name: "D.C.", id: "DC"},
{name: "Delaware", id: "DE"},
{name: "Florida", id: "FL"},
{name: "Georgia", id: "GA"},
{name: "Hawaii", id: "HI"},
{name: "Idaho", id: "ID"},
{name: "Illinois", id: "IL"},
{name: "Indiana", id: "IN"},
{name: "Iowa", id: "IA"},
{name: "Kansas", id: "KS"},
{name: "Kentucky", id: "KY"},
{name: "Louisiana", id: "LA"},
{name: "Maine", id: "ME"},
{name: "Maryland", id: "MD"},
{name: "Massachusetts", id: "MA"},
{name: "Michigan", id: "MI"},
{name: "Minnesota", id: "MN"},
{name: "Mississippi", id: "MS"},
{name: "Missouri", id: "MO"},
{name: "Montana", id: "MT"},
{name: "Nebraska", id: "NE"},
{name: "Nevada", id: "NV"},
{name: "New Hampshire", id: "NH"},
{name: "New Jersey", id: "NJ"},
{name: "New Mexico", id: "NM"},
{name: "New York", id: "NY"},
{name: "North Carolina", id: "NC"},
{name: "North Dakota", id: "ND"},
{name: "Ohio", id: "OH"},
{name: "Oklahoma", id: "OK"},
{name: "Oregon", id: "OR"},
{name: "Pennsylvenia", id: "PA"},
{name: "Rhode Island", id: "RI"},
{name: "South Carolina", id: "SC"},
{name: "South Dakota", id: "SD"},
{name: "Tennessee", id: "TN"},
{name: "Texas", id: "TX"},
{name: "Utah", id: "UT"},
{name: "Vermont", id: "VT"},
{name: "Virginia", id: "VA"},
{name: "Washington", id: "WA"},
{name: "West Virginia", id: "WV"},
{name: "Wisconsin", id: "WI"},
{name: "Wyoming", id: "WY"}
];


for(var x = 0, y=allStates.length; x<y; x++){
    var markUp = Math.round(Math.random()*999999),
        markDwn = Math.round(Math.random()*999999),
        cstMup = Math.round(Math.random()*99999),
        cstMdn = Math.round(Math.random()*99999),
        nameID = allStates[x].nameID,
        mapID = allStates[x].mapID,
        stateID = stateNames[x]?stateNames[x].id:'NA',
        rgnName = stateNames[x]?stateNames[x].name:'undefined'
    
    allStates[x] = {
        markUp: markUp,
        markDwn: markDwn,
        cstMup: cstMup,
        cstMdn: cstMdn,
        nameID: nameID,
        mapID: mapID,        
        stateID: stateID,
        rgnName: rgnName
    }
}